- name: install mongodb component
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongo repo to yum.repo.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb-org
    ansible.builtin.yum:
      name: mongodb-org
      state: installed